### PR TITLE
Fh 2693

### PR DESCRIPTION
**Pull request by secondsun**
See $TITLE JIra.

### CODE REVIEW

**Comment by matskiv** [comment]
This fix works :+1:

**Comment by secondsun** [comment]
@corinnekrych @edewit Do we want to ship this fix as is?  I don't like blocking the application startup, but this fix does work at the moment..

**Comment by edewit** [comment]
@secondsun yeah delaying startup is not great, but our testing environments are a lot slower then prod, so I think it's fine +1

**Comment by matzew** [comment]
👍

**Comment by matzew** [comment]
hehe - late here :)

**Pull request merged**
