### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by danielpassos**
# How can I test it (without install the whole app studio)?
1. Build [FH Android SDK PR/29](https://github.com/feedhenry/fh-android-sdk/pull/29) locally
2. Create an application in studio (online)
3. Create an application in UPS 
4. Create an `fh.properties` file in `src/main/assets` with

```
appid=???
appkey=???
host=???
projectid=???

PUSH_SERVER_URL=???
PUSH_SENDER_ID=???
PUSH_VARIANT=???
PUSH_SECRET=???
```

PS: README coming soon (in another PR)

### CODE REVIEW

**Comment by danielpassos** [comment]
@matzew @sebastienblanc @secondsun @wei-lee Could you give it a spin?

**Comment by secondsun** [comment]
Worked for me.  I guess there isn't a version of the studio running with UPS embdeed somewhere for me to test that?

**Comment by wei-lee** [comment]
No, I don't think so. Does anyone have UPS and studio running locally can verify this?

**Comment by corinnekrych** [comment]
@danielpassos why is  app/src/main/assets/fh.properties part of .gitignore?
For iOS it's part of the commit. For iOS, I haven't test the full chain yet but i can test with fh-studio that your project template get created correctly and the values get set in fh.properties correctly. We can test the ups send message from a standalone UPS. 

@danielpassos All you need to do it add you template to https://github.com/corinnekrych/template-config/blob/ups.template.app/global.json#L79

Let me test...

**Comment by danielpassos** [comment]
@corinnekrych Hrm. Let me remove `fh.properties` from .gitignore. I added it to prevent I send it to template repo :D

I'm waiting we merge it first to add in template config. wdyt?

**Comment by corinnekrych** [comment]
@danielpassos it's easier to test template to get a build release number from Bob, for now i've just put your local repo, before merging the PR we'll put the actual path.
https://github.com/feedhenry/template-config/pull/39

**Comment by corinnekrych** [comment]
@danielpassos Reviewed, here is a PR for you to merge: https://github.com/danielpassos/pushstarter-android-app/pull/1

+1 to merge it once you included my changes

**Comment by danielpassos** [comment]
@wei-lee I don't have studio locally to test it

@corinnekrych Done. Thanks!

**Comment by danielpassos** [comment]
Added FH Android SDK 2.3.1 dependency using my [self hosted Maven repo](https://github.com/danielpassos/fh-android-sdk-repository) in my Github account.

**Comment by matzew** [comment]
@johnfriz @jasonmadigan I'd prefer this being hosted on feedhenry GH organization

**Comment by johnfriz** [comment]
@matzew - can I ask why? Is this not a template app?

**Comment by danielpassos** [comment]
@johnfriz I think @matzew was talking about my [Add self hosted Maven repo](https://github.com/danielpassos/pushstarter-android-app/commit/db05bb3fe743115b16f9cd10b7ceee667ea33456) not about this template :)

**Comment by matzew** [comment]
right - the repo, to server the maven artifacts

Instead of a private account, I'd think it should come from feedhenry account/org.

**Comment by johnfriz** [comment]
+1

What's the easiest way to transfer this repo?

**Comment by danielpassos** [comment]
@johnfriz @matzew [Repo created](https://github.com/feedhenry/fh-android-sdk-repository), [PR sent](https://github.com/feedhenry/fh-android-sdk-repository/pull/1)

**Comment by danielpassos** [comment]
@wei-lee @johnfriz @matzew Ready to go. Any comment?

**Comment by wei-lee** [comment]
:rocket:

**Pull request merged**
