### PR TITLE
For convenience auto enable Android-Push Metrics for UPS

### PR DESCRIPTION
**Pull request by matzew**
@danielpassos can you take a look and test this ?

### CODE REVIEW

**Comment by danielpassos** [comment]
@matzew I'll review/merge that after I finish all I need to support Android M

**Comment by danielpassos** [comment]
@matzew Could you rebase that to trigger @travis-ci

**Comment by matzew** [comment]
@danielpassos yo! Done!

**Comment by matzew** [comment]
@danielpassos any comments on this ?

**Comment by danielpassos** [comment]
:+1:

**Pull request merged**
